# Generated by Django 3.2.6 on 2021-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_favorite_bacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='longest',
            field=models.IntegerField(default='0'),
        ),
    ]
