# Generated by Django 3.2.6 on 2021-09-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_favorite_bacon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_bacon',
        ),
    ]
