# Generated by Django 3.2.6 on 2021-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next_step',
            field=models.IntegerField(),
        ),
    ]
