# Generated by Django 3.2.6 on 2021-08-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_step_next_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='next_step',
        ),
    ]
