# Generated by Django 3.2.6 on 2021-08-16 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0004_step_next_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'user')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_people', through='routes.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
