# Generated by Django 3.2.6 on 2021-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_fav_bacon_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='bacon_number',
        ),
        migrations.AddField(
            model_name='person',
            name='bacon_number',
            field=models.IntegerField(default='3', null=True),
        ),
    ]
