# Generated by Django 3.2.6 on 2021-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20210822_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='real_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
