# Generated by Django 3.2.6 on 2021-08-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_person_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='real_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
