# Generated by Django 3.2.6 on 2021-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_movie_real_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='img_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
