# Generated by Django 3.2.6 on 2021-08-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20210824_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img_path',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
