# Generated by Django 4.1.5 on 2023-01-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0013_alter_person_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='found_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='number_of_searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.IntegerField(unique=True),
        ),
    ]
